Add files via upload
adafruit/Adafruit_CircuitPython_PyPortal pull request #83
Opened 2020-08-31 21:22 UTC by cjsieh

Change from adafruit_sdcard to sdcardio .

2020-08-31 21:25 UTC, cjsieh commented
This is for Issue #3309 .  Note that adafruit_sdcard has issues and fails on the PyPortal and PyGamer.

2020-08-31 21:38 UTC, cjsieh commented
pylint errors because of upgrade of pylinit to 2.6.0 .

2020-08-31 21:50 UTC, ladyada commented
@makermelissa hey hey this needs the new exceptionizalation

2020-08-31 22:32 UTC, makermelissa commented
Ok, should be quick. I'll submit a PR.

2020-08-31 22:47 UTC, makermelissa commented
The pylint updates are now merged in. @cjsieh, please pull in latest changes from repo and push again.

2020-09-04 01:52 UTC, FoamyGuy commented
I think the previous actions issue was a temporary problem. Something in the installing dependencies section failed to download the proper file. I re-ran the jobs and it did get past that issue. 

After that it did need one minor change in the docs config file to include `sdcardio` in the list of mocked imports.

2020-09-04 02:24 UTC, FoamyGuy approved these changes
I tested this successfully on 
`Adafruit CircuitPython 6.0.0-alpha.3 on 2020-08-28; Adafruit PyPortal with samd51j20`

Ordinarily I would think we'd want some sort of backwards compatibility since `sdcardio` is not in a stable release yet. But it wasn't working previous as noted by the issue on the core repo noted above. Maybe something could be done in adafruit_sdcard to fix it and then backward compatibility could be provided here. 

This looks good to me. Thanks for this fix @cjsieh!

I am curious if anyone else has thoughts or ideas about the backward compatibility aspect of it. If we merge this then the library will crash on `5.3.1`. It would need to be used with a newer alpha release at this time.

2020-09-08 20:22 UTC, tannewt requested changes
Until 6.0.0 is stable I think we want this to be backwards compatible because it does work for many uses on 5.3.1. I've commented what needs to be changed for backwards compatibility I think.

2020-09-08 20:22 UTC, tannewt commented on adafruit_pyportal.py
> +import sdcardio
```suggestion
try:
  import sdcardio
  native_sd = True
except ImportError:
  import adafruit_sdcard as sdcardio
  native_sd = False
```

2020-09-08 20:22 UTC, tannewt commented on adafruit_pyportal.py
> +        sd_cs = board.SD_CS
```suggestion
        sd_cs = board.SD_CS
        if not native_sd:
          sd_cs = DigitalInOut(sd_cs)
```

2020-09-10 19:16 UTC, tannewt approved these changes
Thank you!

2020-09-10 19:16 UTC, tannewt commented
@FoamyGuy Mind retesting this? Thanks!

2020-09-10 22:44 UTC, FoamyGuy commented
I retested this. Still working successfully on `6.0.0-alpha.3` and no longer crashes on import on `5.3.1`.

2020-09-10 22:47 UTC, merged